# Default values for diatrack-poller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.intranet.gradata.com.au/diatrack-poller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

dexcomPoller:
  maxAccountQuerySize: 10000
  maxConcurrentRequests: 10
  maxQueryPeriodSeconds: 10
  bglQueryFrequencySeconds: 10
  bglAccountRefreshIntervalSeconds: 60
  bglMaxWindowMinutes: 1440 # 24 hours x 60 mins
  bglMaxReadings: 288 # bglMaxWindowMinutes / 5 (Dexcom data interval)

elastic:
  forwardingWorkers: 4
  forwardingBatchSize: 1000

logging:
  console:
    enabled: true
  file:
    enabled: true
    rollingInterval: Day # Infinite|Year|Month|Day|Hour|Minute

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
